image: python:3.10

pipelines:
  default:
    - step:
        name: build
        script:
          - python3 -m venv venv # Create Virtual Environment
          - source venv/bin/activate # Activate Virtual Environment
          - pip install -r requirements.txt #  Install Dependencies
    - step:
        name: Deploy to Railway
        deployment: production
        script:
          - bash <(curl -fsSL cli.new) # Install Railway CLI
          - RAILWAY_TOKEN=$RAILWAY_TOKEN railway up # Deploy to Railway