[build]
builder = "DOCKERFILE"
#buildCommand = "gunicorn \"brew:create_app()\""
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartrestartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5